os: linux
dist: xenial
language: node_js
notifications:
    email:
        recipients:
            - kappelt.peter@gmail.com
        on_success: always
        on_failure: always
services:
    - docker
node_js:
    - '12'
branches:
  only:
    - dev
    - /^release-.*$/
    - /[\d]+\.[\d]+\.[\d]/
cache:
  directories:
    - node_modules
deploy:
    provider: npm
    skip_cleanup: true
    api_key: $NPM_TOKEN
    email: kappelt.peter@gmail.com
    on:
        tags: true
before_install:
    - export VERSION=$(cat VERSION)
    - npm update
install:
    - npm install
script:
    - npm run doc